services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=air_quality
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/air_quality
      - RUST_LOG=info
      - OPENAQ_KEY=${OPENAQ_KEY} # Pass API key from host environment
    depends_on:
      database:
        condition: service_healthy
    # Removed volume mount to use the compiled binary from the Docker image
    # The command here is just a default, can be overridden
    command: ["import", "--days", "5"]

volumes:
  postgres_data:
